movie/app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from app import views

app_name='movie'
urlpatterns = [
    # path('',views.home,name="home"),
    # path('add',views.add,name="add"),
    # path('detail/<int:p>',views.detail,name="detail"),
    # path('update/<int:p>',views.update,name="update"),
    # path('delete/<int:p>',views.delete,name="delete"),

    # class based
    path('',views.MovieList.as_view(),name="home"),
    path('detail/<int:pk>',views.MovieDetail.as_view(),name="detail"),
    path('add',views.MovieAdd.as_view(),name="add"),
    path('update/<int:pk>',views.MovieUpdate.as_view(),name="update"),
    path('delete/<int:pk>',views.MovieDelete.as_view(),name="delete")
]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title=models.CharField(max_length=40)
    director=models.CharField(max_length=40)
    description=models.CharField(max_length=100)
    image=models.FileField(upload_to='image',null=True,blank=True)
    def __str__(self):
        return self.title

movie/app/forms.py
from django import forms
from app.models import Movie

class bookform(forms.ModelForm):
    class Meta:
        model=Movie
        fields="__all__"

movie/app/views.py
from django.shortcuts import render,redirect
from app.forms import bookform
from app.models import Movie
from django.urls import reverse_lazy
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView


# Create your views here.
# def home(request):
#     k=Movie.objects.all()
#     return render(request,'home.html',{'b':k})


class MovieList(ListView):
    model = Movie
    template_name = "home.html"
    context_object_name = "b"


# def add(request):
#     if (request.method=="POST"):
#         form=bookform(request.POST,request.FILES)
#         if form.is_valid():
#             form.save()
#             return home(request)
#     form=bookform()
#     return render(request,'addmovie.html',{'form':form})


class MovieAdd(CreateView):
    model = Movie
    template_name = "addmovie.html"
    fields = '__all__'
    success_url = reverse_lazy('movie:home')


# def detail(request,p):
#     k=Movie.objects.get(id=p)
#     return render(request,'detail.html',{'b':k})


class MovieDetail(DetailView):
    model = Movie
    template_name = 'detail.html'
    context_object_name = 'b'


# def update(request,p):
#     m=Movie.objects.get(id=p)
#     if(request.method=="POST"):
#         form=bookform(request.POST,request.FILES,instance=m)
#         if form.is_valid():
#             form.save()
#             return home(request)
#     form=bookform(instance=m)
#     return render(request,'update.html',{'form':form})


class MovieUpdate(UpdateView):
    model = Movie
    template_name = 'update.html'
    fields = "__all__"
    success_url = reverse_lazy('movie:home')


# def delete(request,p):
#     m=Movie.objects.get(id=p)
#     m.delete()
#     return redirect('movie:home')


class MovieDelete(DeleteView):
    model = Movie
    success_url = reverse_lazy('movie:home')
    template_name = 'delete.html'

movie/templates/addmovie.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<!--<center>-->
<!--    <form method="POST" enctype="multipart/form-data">-->
<!--        {% csrf_token %}-->
<!--    <h2>Add Movie</h2>-->
<!--    <table>-->
<!--        {{form.as_table}}-->
<!--    </table><br>-->
<!--    <input class="btn btn-outline-success" type="submit" value="Submit">-->
<!--    </form>-->
<!--</center>-->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid mx-3">
    <a class="navbar-brand btn btn-outline-success" href="{% url 'movie:home' %}">HOME</a>
    <div class="d-flex mx-5">
      <a class="btn btn-outline-success" href="{% url 'movie:add' %}">Add Movie</a>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Are you sure want to delete???</p>
    <input type="submit" class="btn btn-outline-primary">
</form>
{% endblock %}

movie/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row m-5">
    <div class="col-4">
        <img src="{{b.image.url}}" width="240px" height="360px">
    </div>
    <div class="col-8">
        <h3>{{b.title}}</h3>
        <h5>Director: {{b.director}}</h5>
        <p>{{b.description}}</p>
        <a href="{% url 'movie:update' b.id %}" class="btn btn-outline-success">Update</a>
        <a href="{% url 'movie:delete' b.id %}" class="btn btn-outline-danger">Delete</a>
    </div>
</div>
{% endblock %}

movie/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center">Movies</h2>
<div class="container"  style="display:flex;justify-content:center;align-items:center;">
<div class="row">
{% for i in b %}
  <div class="col-3 mb-5 mx-auto">
  <div class="card" style="width: 15rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="..." width="100px" height="300px">
  <div class="card-body">
    <h5 class="card-title">{{i.title}}</h5>
      <h6 class="card-title">{{i.director}}</h6>
    <p class="card-text">{{i.description}}</p>
    <a href="{% url 'movie:detail' i.id %}" class="btn btn-outline-success">Details</a>
  </div>
  </div>
  </div>
{% endfor %}
  </div>
  </div>
{% endblock %}

movie/templates/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<!--<center>-->
<!--    <form method="POST" enctype="multipart/form-data">-->
<!--        {% csrf_token %}-->
<!--    <h2>Add Movie</h2>-->
<!--    <table>-->
<!--        {{form.as_table}}-->
<!--    </table><br>-->
<!--    <input class="btn btn-outline-success" type="submit" value="Submit">-->
<!--    </form>-->
<!--</center>-->
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}